// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map/map_parking_space.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "map/map_parking_space.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace apollo {
namespace hdmap {

namespace {

const ::google::protobuf::Descriptor* ParkingSpace_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ParkingSpace_reflection_ = NULL;
const ::google::protobuf::Descriptor* ParkingLot_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ParkingLot_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_map_2fmap_5fparking_5fspace_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_map_2fmap_5fparking_5fspace_2eproto() {
  protobuf_AddDesc_map_2fmap_5fparking_5fspace_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "map/map_parking_space.proto");
  GOOGLE_CHECK(file != NULL);
  ParkingSpace_descriptor_ = file->message_type(0);
  static const int ParkingSpace_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParkingSpace, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParkingSpace, polygon_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParkingSpace, overlap_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParkingSpace, heading_),
  };
  ParkingSpace_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ParkingSpace_descriptor_,
      ParkingSpace::default_instance_,
      ParkingSpace_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParkingSpace, _has_bits_[0]),
      -1,
      -1,
      sizeof(ParkingSpace),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParkingSpace, _internal_metadata_),
      -1);
  ParkingLot_descriptor_ = file->message_type(1);
  static const int ParkingLot_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParkingLot, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParkingLot, polygon_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParkingLot, overlap_id_),
  };
  ParkingLot_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ParkingLot_descriptor_,
      ParkingLot::default_instance_,
      ParkingLot_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParkingLot, _has_bits_[0]),
      -1,
      -1,
      sizeof(ParkingLot),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParkingLot, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_map_2fmap_5fparking_5fspace_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ParkingSpace_descriptor_, &ParkingSpace::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ParkingLot_descriptor_, &ParkingLot::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_map_2fmap_5fparking_5fspace_2eproto() {
  delete ParkingSpace::default_instance_;
  delete ParkingSpace_reflection_;
  delete ParkingLot::default_instance_;
  delete ParkingLot_reflection_;
}

void protobuf_AddDesc_map_2fmap_5fparking_5fspace_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_map_2fmap_5fparking_5fspace_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::apollo::hdmap::protobuf_AddDesc_map_2fmap_5fgeometry_2eproto();
  ::apollo::hdmap::protobuf_AddDesc_map_2fmap_5fid_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\033map/map_parking_space.proto\022\014apollo.hd"
    "map\032\026map/map_geometry.proto\032\020map/map_id."
    "proto\"\213\001\n\014ParkingSpace\022\034\n\002id\030\001 \001(\0132\020.apo"
    "llo.hdmap.Id\022&\n\007polygon\030\002 \001(\0132\025.apollo.h"
    "dmap.Polygon\022$\n\noverlap_id\030\003 \003(\0132\020.apoll"
    "o.hdmap.Id\022\017\n\007heading\030\004 \001(\001\"x\n\nParkingLo"
    "t\022\034\n\002id\030\001 \001(\0132\020.apollo.hdmap.Id\022&\n\007polyg"
    "on\030\002 \001(\0132\025.apollo.hdmap.Polygon\022$\n\noverl"
    "ap_id\030\003 \003(\0132\020.apollo.hdmap.Id", 349);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "map/map_parking_space.proto", &protobuf_RegisterTypes);
  ParkingSpace::default_instance_ = new ParkingSpace();
  ParkingLot::default_instance_ = new ParkingLot();
  ParkingSpace::default_instance_->InitAsDefaultInstance();
  ParkingLot::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_map_2fmap_5fparking_5fspace_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_map_2fmap_5fparking_5fspace_2eproto {
  StaticDescriptorInitializer_map_2fmap_5fparking_5fspace_2eproto() {
    protobuf_AddDesc_map_2fmap_5fparking_5fspace_2eproto();
  }
} static_descriptor_initializer_map_2fmap_5fparking_5fspace_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ParkingSpace::kIdFieldNumber;
const int ParkingSpace::kPolygonFieldNumber;
const int ParkingSpace::kOverlapIdFieldNumber;
const int ParkingSpace::kHeadingFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ParkingSpace::ParkingSpace()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.hdmap.ParkingSpace)
}

void ParkingSpace::InitAsDefaultInstance() {
  id_ = const_cast< ::apollo::hdmap::Id*>(&::apollo::hdmap::Id::default_instance());
  polygon_ = const_cast< ::apollo::hdmap::Polygon*>(&::apollo::hdmap::Polygon::default_instance());
}

ParkingSpace::ParkingSpace(const ParkingSpace& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:apollo.hdmap.ParkingSpace)
}

void ParkingSpace::SharedCtor() {
  _cached_size_ = 0;
  id_ = NULL;
  polygon_ = NULL;
  heading_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ParkingSpace::~ParkingSpace() {
  // @@protoc_insertion_point(destructor:apollo.hdmap.ParkingSpace)
  SharedDtor();
}

void ParkingSpace::SharedDtor() {
  if (this != default_instance_) {
    delete id_;
    delete polygon_;
  }
}

void ParkingSpace::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ParkingSpace::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ParkingSpace_descriptor_;
}

const ParkingSpace& ParkingSpace::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_map_2fmap_5fparking_5fspace_2eproto();
  return *default_instance_;
}

ParkingSpace* ParkingSpace::default_instance_ = NULL;

ParkingSpace* ParkingSpace::New(::google::protobuf::Arena* arena) const {
  ParkingSpace* n = new ParkingSpace;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ParkingSpace::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.hdmap.ParkingSpace)
  if (_has_bits_[0 / 32] & 11u) {
    if (has_id()) {
      if (id_ != NULL) id_->::apollo::hdmap::Id::Clear();
    }
    if (has_polygon()) {
      if (polygon_ != NULL) polygon_->::apollo::hdmap::Polygon::Clear();
    }
    heading_ = 0;
  }
  overlap_id_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool ParkingSpace::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.hdmap.ParkingSpace)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .apollo.hdmap.Id id = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_id()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_polygon;
        break;
      }

      // optional .apollo.hdmap.Polygon polygon = 2;
      case 2: {
        if (tag == 18) {
         parse_polygon:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_polygon()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_overlap_id;
        break;
      }

      // repeated .apollo.hdmap.Id overlap_id = 3;
      case 3: {
        if (tag == 26) {
         parse_overlap_id:
          DO_(input->IncrementRecursionDepth());
         parse_loop_overlap_id:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_overlap_id()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_loop_overlap_id;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectTag(33)) goto parse_heading;
        break;
      }

      // optional double heading = 4;
      case 4: {
        if (tag == 33) {
         parse_heading:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &heading_)));
          set_has_heading();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.hdmap.ParkingSpace)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.hdmap.ParkingSpace)
  return false;
#undef DO_
}

void ParkingSpace::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.hdmap.ParkingSpace)
  // optional .apollo.hdmap.Id id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->id_, output);
  }

  // optional .apollo.hdmap.Polygon polygon = 2;
  if (has_polygon()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->polygon_, output);
  }

  // repeated .apollo.hdmap.Id overlap_id = 3;
  for (unsigned int i = 0, n = this->overlap_id_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->overlap_id(i), output);
  }

  // optional double heading = 4;
  if (has_heading()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->heading(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.hdmap.ParkingSpace)
}

::google::protobuf::uint8* ParkingSpace::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.hdmap.ParkingSpace)
  // optional .apollo.hdmap.Id id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->id_, false, target);
  }

  // optional .apollo.hdmap.Polygon polygon = 2;
  if (has_polygon()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->polygon_, false, target);
  }

  // repeated .apollo.hdmap.Id overlap_id = 3;
  for (unsigned int i = 0, n = this->overlap_id_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, this->overlap_id(i), false, target);
  }

  // optional double heading = 4;
  if (has_heading()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->heading(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.hdmap.ParkingSpace)
  return target;
}

int ParkingSpace::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.hdmap.ParkingSpace)
  int total_size = 0;

  if (_has_bits_[0 / 32] & 11u) {
    // optional .apollo.hdmap.Id id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->id_);
    }

    // optional .apollo.hdmap.Polygon polygon = 2;
    if (has_polygon()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->polygon_);
    }

    // optional double heading = 4;
    if (has_heading()) {
      total_size += 1 + 8;
    }

  }
  // repeated .apollo.hdmap.Id overlap_id = 3;
  total_size += 1 * this->overlap_id_size();
  for (int i = 0; i < this->overlap_id_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->overlap_id(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ParkingSpace::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.hdmap.ParkingSpace)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ParkingSpace* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ParkingSpace>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.hdmap.ParkingSpace)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.hdmap.ParkingSpace)
    MergeFrom(*source);
  }
}

void ParkingSpace::MergeFrom(const ParkingSpace& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.hdmap.ParkingSpace)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  overlap_id_.MergeFrom(from.overlap_id_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      mutable_id()->::apollo::hdmap::Id::MergeFrom(from.id());
    }
    if (from.has_polygon()) {
      mutable_polygon()->::apollo::hdmap::Polygon::MergeFrom(from.polygon());
    }
    if (from.has_heading()) {
      set_heading(from.heading());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void ParkingSpace::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.hdmap.ParkingSpace)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ParkingSpace::CopyFrom(const ParkingSpace& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.hdmap.ParkingSpace)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ParkingSpace::IsInitialized() const {

  return true;
}

void ParkingSpace::Swap(ParkingSpace* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ParkingSpace::InternalSwap(ParkingSpace* other) {
  std::swap(id_, other->id_);
  std::swap(polygon_, other->polygon_);
  overlap_id_.UnsafeArenaSwap(&other->overlap_id_);
  std::swap(heading_, other->heading_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ParkingSpace::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ParkingSpace_descriptor_;
  metadata.reflection = ParkingSpace_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ParkingSpace

// optional .apollo.hdmap.Id id = 1;
bool ParkingSpace::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void ParkingSpace::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
void ParkingSpace::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
void ParkingSpace::clear_id() {
  if (id_ != NULL) id_->::apollo::hdmap::Id::Clear();
  clear_has_id();
}
const ::apollo::hdmap::Id& ParkingSpace::id() const {
  // @@protoc_insertion_point(field_get:apollo.hdmap.ParkingSpace.id)
  return id_ != NULL ? *id_ : *default_instance_->id_;
}
::apollo::hdmap::Id* ParkingSpace::mutable_id() {
  set_has_id();
  if (id_ == NULL) {
    id_ = new ::apollo::hdmap::Id;
  }
  // @@protoc_insertion_point(field_mutable:apollo.hdmap.ParkingSpace.id)
  return id_;
}
::apollo::hdmap::Id* ParkingSpace::release_id() {
  // @@protoc_insertion_point(field_release:apollo.hdmap.ParkingSpace.id)
  clear_has_id();
  ::apollo::hdmap::Id* temp = id_;
  id_ = NULL;
  return temp;
}
void ParkingSpace::set_allocated_id(::apollo::hdmap::Id* id) {
  delete id_;
  id_ = id;
  if (id) {
    set_has_id();
  } else {
    clear_has_id();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.hdmap.ParkingSpace.id)
}

// optional .apollo.hdmap.Polygon polygon = 2;
bool ParkingSpace::has_polygon() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void ParkingSpace::set_has_polygon() {
  _has_bits_[0] |= 0x00000002u;
}
void ParkingSpace::clear_has_polygon() {
  _has_bits_[0] &= ~0x00000002u;
}
void ParkingSpace::clear_polygon() {
  if (polygon_ != NULL) polygon_->::apollo::hdmap::Polygon::Clear();
  clear_has_polygon();
}
const ::apollo::hdmap::Polygon& ParkingSpace::polygon() const {
  // @@protoc_insertion_point(field_get:apollo.hdmap.ParkingSpace.polygon)
  return polygon_ != NULL ? *polygon_ : *default_instance_->polygon_;
}
::apollo::hdmap::Polygon* ParkingSpace::mutable_polygon() {
  set_has_polygon();
  if (polygon_ == NULL) {
    polygon_ = new ::apollo::hdmap::Polygon;
  }
  // @@protoc_insertion_point(field_mutable:apollo.hdmap.ParkingSpace.polygon)
  return polygon_;
}
::apollo::hdmap::Polygon* ParkingSpace::release_polygon() {
  // @@protoc_insertion_point(field_release:apollo.hdmap.ParkingSpace.polygon)
  clear_has_polygon();
  ::apollo::hdmap::Polygon* temp = polygon_;
  polygon_ = NULL;
  return temp;
}
void ParkingSpace::set_allocated_polygon(::apollo::hdmap::Polygon* polygon) {
  delete polygon_;
  polygon_ = polygon;
  if (polygon) {
    set_has_polygon();
  } else {
    clear_has_polygon();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.hdmap.ParkingSpace.polygon)
}

// repeated .apollo.hdmap.Id overlap_id = 3;
int ParkingSpace::overlap_id_size() const {
  return overlap_id_.size();
}
void ParkingSpace::clear_overlap_id() {
  overlap_id_.Clear();
}
const ::apollo::hdmap::Id& ParkingSpace::overlap_id(int index) const {
  // @@protoc_insertion_point(field_get:apollo.hdmap.ParkingSpace.overlap_id)
  return overlap_id_.Get(index);
}
::apollo::hdmap::Id* ParkingSpace::mutable_overlap_id(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.hdmap.ParkingSpace.overlap_id)
  return overlap_id_.Mutable(index);
}
::apollo::hdmap::Id* ParkingSpace::add_overlap_id() {
  // @@protoc_insertion_point(field_add:apollo.hdmap.ParkingSpace.overlap_id)
  return overlap_id_.Add();
}
::google::protobuf::RepeatedPtrField< ::apollo::hdmap::Id >*
ParkingSpace::mutable_overlap_id() {
  // @@protoc_insertion_point(field_mutable_list:apollo.hdmap.ParkingSpace.overlap_id)
  return &overlap_id_;
}
const ::google::protobuf::RepeatedPtrField< ::apollo::hdmap::Id >&
ParkingSpace::overlap_id() const {
  // @@protoc_insertion_point(field_list:apollo.hdmap.ParkingSpace.overlap_id)
  return overlap_id_;
}

// optional double heading = 4;
bool ParkingSpace::has_heading() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void ParkingSpace::set_has_heading() {
  _has_bits_[0] |= 0x00000008u;
}
void ParkingSpace::clear_has_heading() {
  _has_bits_[0] &= ~0x00000008u;
}
void ParkingSpace::clear_heading() {
  heading_ = 0;
  clear_has_heading();
}
 double ParkingSpace::heading() const {
  // @@protoc_insertion_point(field_get:apollo.hdmap.ParkingSpace.heading)
  return heading_;
}
 void ParkingSpace::set_heading(double value) {
  set_has_heading();
  heading_ = value;
  // @@protoc_insertion_point(field_set:apollo.hdmap.ParkingSpace.heading)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ParkingLot::kIdFieldNumber;
const int ParkingLot::kPolygonFieldNumber;
const int ParkingLot::kOverlapIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ParkingLot::ParkingLot()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.hdmap.ParkingLot)
}

void ParkingLot::InitAsDefaultInstance() {
  id_ = const_cast< ::apollo::hdmap::Id*>(&::apollo::hdmap::Id::default_instance());
  polygon_ = const_cast< ::apollo::hdmap::Polygon*>(&::apollo::hdmap::Polygon::default_instance());
}

ParkingLot::ParkingLot(const ParkingLot& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:apollo.hdmap.ParkingLot)
}

void ParkingLot::SharedCtor() {
  _cached_size_ = 0;
  id_ = NULL;
  polygon_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ParkingLot::~ParkingLot() {
  // @@protoc_insertion_point(destructor:apollo.hdmap.ParkingLot)
  SharedDtor();
}

void ParkingLot::SharedDtor() {
  if (this != default_instance_) {
    delete id_;
    delete polygon_;
  }
}

void ParkingLot::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ParkingLot::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ParkingLot_descriptor_;
}

const ParkingLot& ParkingLot::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_map_2fmap_5fparking_5fspace_2eproto();
  return *default_instance_;
}

ParkingLot* ParkingLot::default_instance_ = NULL;

ParkingLot* ParkingLot::New(::google::protobuf::Arena* arena) const {
  ParkingLot* n = new ParkingLot;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ParkingLot::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.hdmap.ParkingLot)
  if (_has_bits_[0 / 32] & 3u) {
    if (has_id()) {
      if (id_ != NULL) id_->::apollo::hdmap::Id::Clear();
    }
    if (has_polygon()) {
      if (polygon_ != NULL) polygon_->::apollo::hdmap::Polygon::Clear();
    }
  }
  overlap_id_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool ParkingLot::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.hdmap.ParkingLot)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .apollo.hdmap.Id id = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_id()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_polygon;
        break;
      }

      // optional .apollo.hdmap.Polygon polygon = 2;
      case 2: {
        if (tag == 18) {
         parse_polygon:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_polygon()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_overlap_id;
        break;
      }

      // repeated .apollo.hdmap.Id overlap_id = 3;
      case 3: {
        if (tag == 26) {
         parse_overlap_id:
          DO_(input->IncrementRecursionDepth());
         parse_loop_overlap_id:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_overlap_id()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_loop_overlap_id;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.hdmap.ParkingLot)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.hdmap.ParkingLot)
  return false;
#undef DO_
}

void ParkingLot::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.hdmap.ParkingLot)
  // optional .apollo.hdmap.Id id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->id_, output);
  }

  // optional .apollo.hdmap.Polygon polygon = 2;
  if (has_polygon()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->polygon_, output);
  }

  // repeated .apollo.hdmap.Id overlap_id = 3;
  for (unsigned int i = 0, n = this->overlap_id_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->overlap_id(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.hdmap.ParkingLot)
}

::google::protobuf::uint8* ParkingLot::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.hdmap.ParkingLot)
  // optional .apollo.hdmap.Id id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->id_, false, target);
  }

  // optional .apollo.hdmap.Polygon polygon = 2;
  if (has_polygon()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->polygon_, false, target);
  }

  // repeated .apollo.hdmap.Id overlap_id = 3;
  for (unsigned int i = 0, n = this->overlap_id_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, this->overlap_id(i), false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.hdmap.ParkingLot)
  return target;
}

int ParkingLot::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.hdmap.ParkingLot)
  int total_size = 0;

  if (_has_bits_[0 / 32] & 3u) {
    // optional .apollo.hdmap.Id id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->id_);
    }

    // optional .apollo.hdmap.Polygon polygon = 2;
    if (has_polygon()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->polygon_);
    }

  }
  // repeated .apollo.hdmap.Id overlap_id = 3;
  total_size += 1 * this->overlap_id_size();
  for (int i = 0; i < this->overlap_id_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->overlap_id(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ParkingLot::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.hdmap.ParkingLot)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ParkingLot* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ParkingLot>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.hdmap.ParkingLot)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.hdmap.ParkingLot)
    MergeFrom(*source);
  }
}

void ParkingLot::MergeFrom(const ParkingLot& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.hdmap.ParkingLot)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  overlap_id_.MergeFrom(from.overlap_id_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      mutable_id()->::apollo::hdmap::Id::MergeFrom(from.id());
    }
    if (from.has_polygon()) {
      mutable_polygon()->::apollo::hdmap::Polygon::MergeFrom(from.polygon());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void ParkingLot::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.hdmap.ParkingLot)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ParkingLot::CopyFrom(const ParkingLot& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.hdmap.ParkingLot)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ParkingLot::IsInitialized() const {

  return true;
}

void ParkingLot::Swap(ParkingLot* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ParkingLot::InternalSwap(ParkingLot* other) {
  std::swap(id_, other->id_);
  std::swap(polygon_, other->polygon_);
  overlap_id_.UnsafeArenaSwap(&other->overlap_id_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ParkingLot::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ParkingLot_descriptor_;
  metadata.reflection = ParkingLot_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ParkingLot

// optional .apollo.hdmap.Id id = 1;
bool ParkingLot::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void ParkingLot::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
void ParkingLot::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
void ParkingLot::clear_id() {
  if (id_ != NULL) id_->::apollo::hdmap::Id::Clear();
  clear_has_id();
}
const ::apollo::hdmap::Id& ParkingLot::id() const {
  // @@protoc_insertion_point(field_get:apollo.hdmap.ParkingLot.id)
  return id_ != NULL ? *id_ : *default_instance_->id_;
}
::apollo::hdmap::Id* ParkingLot::mutable_id() {
  set_has_id();
  if (id_ == NULL) {
    id_ = new ::apollo::hdmap::Id;
  }
  // @@protoc_insertion_point(field_mutable:apollo.hdmap.ParkingLot.id)
  return id_;
}
::apollo::hdmap::Id* ParkingLot::release_id() {
  // @@protoc_insertion_point(field_release:apollo.hdmap.ParkingLot.id)
  clear_has_id();
  ::apollo::hdmap::Id* temp = id_;
  id_ = NULL;
  return temp;
}
void ParkingLot::set_allocated_id(::apollo::hdmap::Id* id) {
  delete id_;
  id_ = id;
  if (id) {
    set_has_id();
  } else {
    clear_has_id();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.hdmap.ParkingLot.id)
}

// optional .apollo.hdmap.Polygon polygon = 2;
bool ParkingLot::has_polygon() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void ParkingLot::set_has_polygon() {
  _has_bits_[0] |= 0x00000002u;
}
void ParkingLot::clear_has_polygon() {
  _has_bits_[0] &= ~0x00000002u;
}
void ParkingLot::clear_polygon() {
  if (polygon_ != NULL) polygon_->::apollo::hdmap::Polygon::Clear();
  clear_has_polygon();
}
const ::apollo::hdmap::Polygon& ParkingLot::polygon() const {
  // @@protoc_insertion_point(field_get:apollo.hdmap.ParkingLot.polygon)
  return polygon_ != NULL ? *polygon_ : *default_instance_->polygon_;
}
::apollo::hdmap::Polygon* ParkingLot::mutable_polygon() {
  set_has_polygon();
  if (polygon_ == NULL) {
    polygon_ = new ::apollo::hdmap::Polygon;
  }
  // @@protoc_insertion_point(field_mutable:apollo.hdmap.ParkingLot.polygon)
  return polygon_;
}
::apollo::hdmap::Polygon* ParkingLot::release_polygon() {
  // @@protoc_insertion_point(field_release:apollo.hdmap.ParkingLot.polygon)
  clear_has_polygon();
  ::apollo::hdmap::Polygon* temp = polygon_;
  polygon_ = NULL;
  return temp;
}
void ParkingLot::set_allocated_polygon(::apollo::hdmap::Polygon* polygon) {
  delete polygon_;
  polygon_ = polygon;
  if (polygon) {
    set_has_polygon();
  } else {
    clear_has_polygon();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.hdmap.ParkingLot.polygon)
}

// repeated .apollo.hdmap.Id overlap_id = 3;
int ParkingLot::overlap_id_size() const {
  return overlap_id_.size();
}
void ParkingLot::clear_overlap_id() {
  overlap_id_.Clear();
}
const ::apollo::hdmap::Id& ParkingLot::overlap_id(int index) const {
  // @@protoc_insertion_point(field_get:apollo.hdmap.ParkingLot.overlap_id)
  return overlap_id_.Get(index);
}
::apollo::hdmap::Id* ParkingLot::mutable_overlap_id(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.hdmap.ParkingLot.overlap_id)
  return overlap_id_.Mutable(index);
}
::apollo::hdmap::Id* ParkingLot::add_overlap_id() {
  // @@protoc_insertion_point(field_add:apollo.hdmap.ParkingLot.overlap_id)
  return overlap_id_.Add();
}
::google::protobuf::RepeatedPtrField< ::apollo::hdmap::Id >*
ParkingLot::mutable_overlap_id() {
  // @@protoc_insertion_point(field_mutable_list:apollo.hdmap.ParkingLot.overlap_id)
  return &overlap_id_;
}
const ::google::protobuf::RepeatedPtrField< ::apollo::hdmap::Id >&
ParkingLot::overlap_id() const {
  // @@protoc_insertion_point(field_list:apollo.hdmap.ParkingLot.overlap_id)
  return overlap_id_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace hdmap
}  // namespace apollo

// @@protoc_insertion_point(global_scope)
